[package]
name = "e2e"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
insta = "0.16.1"
postgres = "0.19.2"
pretty_env_logger = "0.4"
testcontainers = "0.12.0"
test-generator = "0.3.0"
similar-asserts = "1.2.0"

[build-dependencies]
build-deps = "^0.1"
